sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '10'
scripts:
  - yarn test
  - yarn run build
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
