sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '8'
before_install:
  - yarn global add codecov
scripts:
  - yarn test -- --coverage --coverage-paths src/**/*.js
  - codecov
  - yarn run build
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
