// flow-typed signature: 82866fa911630da1e8e6dd2e4db7cf40
// flow-typed version: <<STUB>>/browsochrones_v^0.9.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browsochrones'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browsochrones' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browsochrones/build/lib/accessibility-for-grid' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/get-spectrogram-data' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/get-surface' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/get-transitive-data' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/grid' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/index' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/isochrone-tile' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/mercator' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/origin' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/propagation' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/stop-tree-cache' {
  declare module.exports: any;
}

declare module 'browsochrones/build/lib/worker-handlers' {
  declare module.exports: any;
}

declare module 'browsochrones/example' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/accessibility-for-grid' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/get-spectrogram-data' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/get-surface' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/get-transitive-data' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/grid' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/index' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/isochrone-tile' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/mercator' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/origin' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/propagation' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/stop-tree-cache' {
  declare module.exports: any;
}

declare module 'browsochrones/lib/worker-handlers' {
  declare module.exports: any;
}

declare module 'browsochrones/test/contour-grid' {
  declare module.exports: any;
}

declare module 'browsochrones/test/index' {
  declare module.exports: any;
}

declare module 'browsochrones/test/marey' {
  declare module.exports: any;
}

declare module 'browsochrones/test/perf' {
  declare module.exports: any;
}

declare module 'browsochrones/test/schematic-line-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browsochrones/build/lib/accessibility-for-grid.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/accessibility-for-grid'>;
}
declare module 'browsochrones/build/lib/get-spectrogram-data.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/get-spectrogram-data'>;
}
declare module 'browsochrones/build/lib/get-surface.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/get-surface'>;
}
declare module 'browsochrones/build/lib/get-transitive-data.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/get-transitive-data'>;
}
declare module 'browsochrones/build/lib/grid.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/grid'>;
}
declare module 'browsochrones/build/lib/index.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/index'>;
}
declare module 'browsochrones/build/lib/isochrone-tile.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/isochrone-tile'>;
}
declare module 'browsochrones/build/lib/mercator.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/mercator'>;
}
declare module 'browsochrones/build/lib/origin.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/origin'>;
}
declare module 'browsochrones/build/lib/propagation.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/propagation'>;
}
declare module 'browsochrones/build/lib/stop-tree-cache.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/stop-tree-cache'>;
}
declare module 'browsochrones/build/lib/worker-handlers.js' {
  declare module.exports: $Exports<'browsochrones/build/lib/worker-handlers'>;
}
declare module 'browsochrones/example.js' {
  declare module.exports: $Exports<'browsochrones/example'>;
}
declare module 'browsochrones/lib/accessibility-for-grid.js' {
  declare module.exports: $Exports<'browsochrones/lib/accessibility-for-grid'>;
}
declare module 'browsochrones/lib/get-spectrogram-data.js' {
  declare module.exports: $Exports<'browsochrones/lib/get-spectrogram-data'>;
}
declare module 'browsochrones/lib/get-surface.js' {
  declare module.exports: $Exports<'browsochrones/lib/get-surface'>;
}
declare module 'browsochrones/lib/get-transitive-data.js' {
  declare module.exports: $Exports<'browsochrones/lib/get-transitive-data'>;
}
declare module 'browsochrones/lib/grid.js' {
  declare module.exports: $Exports<'browsochrones/lib/grid'>;
}
declare module 'browsochrones/lib/index.js' {
  declare module.exports: $Exports<'browsochrones/lib/index'>;
}
declare module 'browsochrones/lib/isochrone-tile.js' {
  declare module.exports: $Exports<'browsochrones/lib/isochrone-tile'>;
}
declare module 'browsochrones/lib/mercator.js' {
  declare module.exports: $Exports<'browsochrones/lib/mercator'>;
}
declare module 'browsochrones/lib/origin.js' {
  declare module.exports: $Exports<'browsochrones/lib/origin'>;
}
declare module 'browsochrones/lib/propagation.js' {
  declare module.exports: $Exports<'browsochrones/lib/propagation'>;
}
declare module 'browsochrones/lib/stop-tree-cache.js' {
  declare module.exports: $Exports<'browsochrones/lib/stop-tree-cache'>;
}
declare module 'browsochrones/lib/worker-handlers.js' {
  declare module.exports: $Exports<'browsochrones/lib/worker-handlers'>;
}
declare module 'browsochrones/test/contour-grid.js' {
  declare module.exports: $Exports<'browsochrones/test/contour-grid'>;
}
declare module 'browsochrones/test/index.js' {
  declare module.exports: $Exports<'browsochrones/test/index'>;
}
declare module 'browsochrones/test/marey.js' {
  declare module.exports: $Exports<'browsochrones/test/marey'>;
}
declare module 'browsochrones/test/perf.js' {
  declare module.exports: $Exports<'browsochrones/test/perf'>;
}
declare module 'browsochrones/test/schematic-line-map.js' {
  declare module.exports: $Exports<'browsochrones/test/schematic-line-map'>;
}
