// flow-typed signature: a7200b253a171e119d0ff14cea46998b
// flow-typed version: <<STUB>>/isomorphic-mapzen-search_v^1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-mapzen-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-mapzen-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-mapzen-search/__tests__/index' {
  declare module.exports: any;
}

declare module 'isomorphic-mapzen-search/build/index' {
  declare module.exports: any;
}

declare module 'isomorphic-mapzen-search/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'isomorphic-mapzen-search/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-mapzen-search/__tests__/index.js' {
  declare module.exports: $Exports<'isomorphic-mapzen-search/__tests__/index'>;
}
declare module 'isomorphic-mapzen-search/build/index.js' {
  declare module.exports: $Exports<'isomorphic-mapzen-search/build/index'>;
}
declare module 'isomorphic-mapzen-search/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'isomorphic-mapzen-search/coverage/lcov-report/prettify'>;
}
declare module 'isomorphic-mapzen-search/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'isomorphic-mapzen-search/coverage/lcov-report/sorter'>;
}
declare module 'isomorphic-mapzen-search/index' {
  declare module.exports: $Exports<'isomorphic-mapzen-search'>;
}
declare module 'isomorphic-mapzen-search/index.js' {
  declare module.exports: $Exports<'isomorphic-mapzen-search'>;
}
