// flow-typed signature: 6a70a1c7fc01570da221dfcb31cffe27
// flow-typed version: <<STUB>>/jsolines_v^1.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsolines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsolines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsolines/__tests__/index' {
  declare module.exports: any;
}

declare module 'jsolines/build/index' {
  declare module.exports: any;
}

declare module 'jsolines/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'jsolines/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsolines/__tests__/index.js' {
  declare module.exports: $Exports<'jsolines/__tests__/index'>;
}
declare module 'jsolines/build/index.js' {
  declare module.exports: $Exports<'jsolines/build/index'>;
}
declare module 'jsolines/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'jsolines/coverage/lcov-report/prettify'>;
}
declare module 'jsolines/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'jsolines/coverage/lcov-report/sorter'>;
}
declare module 'jsolines/index' {
  declare module.exports: $Exports<'jsolines'>;
}
declare module 'jsolines/index.js' {
  declare module.exports: $Exports<'jsolines'>;
}
