// flow-typed signature: 5096c4e36e24c5ce562cd8f6d8e0f68d
// flow-typed version: <<STUB>>/leaflet-transitivelayer_v^0.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-transitivelayer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-transitivelayer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-transitivelayer/TransitiveLayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-transitivelayer/TransitiveLayer.js' {
  declare module.exports: $Exports<'leaflet-transitivelayer/TransitiveLayer'>;
}
