// flow-typed signature: e0ad3938a8da7b7c7fdca95b7600fcbe
// flow-typed version: <<STUB>>/mastarm_v^4.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mastarm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mastarm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mastarm/__mocks__/aws-sdk' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/bin/mastarm' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/babel' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/build' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/jest' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/lint-messages' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/load-config' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/prepublish' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/push-to-s3' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/lib/util' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/test-utils/mocks/index' {
  declare module.exports: any;
}

declare module 'mastarm/__tests__/test-utils/util' {
  declare module.exports: any;
}

declare module 'mastarm/lib/babel-config' {
  declare module.exports: any;
}

declare module 'mastarm/lib/browserify' {
  declare module.exports: any;
}

declare module 'mastarm/lib/budo' {
  declare module.exports: any;
}

declare module 'mastarm/lib/build' {
  declare module.exports: any;
}

declare module 'mastarm/lib/css-transform' {
  declare module.exports: any;
}

declare module 'mastarm/lib/flyle' {
  declare module.exports: any;
}

declare module 'mastarm/lib/fs-promise' {
  declare module.exports: any;
}

declare module 'mastarm/lib/jest-preprocessor' {
  declare module.exports: any;
}

declare module 'mastarm/lib/jest' {
  declare module.exports: any;
}

declare module 'mastarm/lib/js-build' {
  declare module.exports: any;
}

declare module 'mastarm/lib/js-transform' {
  declare module.exports: any;
}

declare module 'mastarm/lib/lint-messages' {
  declare module.exports: any;
}

declare module 'mastarm/lib/load-config' {
  declare module.exports: any;
}

declare module 'mastarm/lib/logger' {
  declare module.exports: any;
}

declare module 'mastarm/lib/pkg' {
  declare module.exports: any;
}

declare module 'mastarm/lib/prepublish' {
  declare module.exports: any;
}

declare module 'mastarm/lib/push-to-s3' {
  declare module.exports: any;
}

declare module 'mastarm/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mastarm/__mocks__/aws-sdk.js' {
  declare module.exports: $Exports<'mastarm/__mocks__/aws-sdk'>;
}
declare module 'mastarm/__tests__/bin/mastarm.js' {
  declare module.exports: $Exports<'mastarm/__tests__/bin/mastarm'>;
}
declare module 'mastarm/__tests__/lib/babel.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/babel'>;
}
declare module 'mastarm/__tests__/lib/build.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/build'>;
}
declare module 'mastarm/__tests__/lib/jest.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/jest'>;
}
declare module 'mastarm/__tests__/lib/lint-messages.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/lint-messages'>;
}
declare module 'mastarm/__tests__/lib/load-config.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/load-config'>;
}
declare module 'mastarm/__tests__/lib/prepublish.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/prepublish'>;
}
declare module 'mastarm/__tests__/lib/push-to-s3.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/push-to-s3'>;
}
declare module 'mastarm/__tests__/lib/util.js' {
  declare module.exports: $Exports<'mastarm/__tests__/lib/util'>;
}
declare module 'mastarm/__tests__/test-utils/mocks/index.js' {
  declare module.exports: $Exports<'mastarm/__tests__/test-utils/mocks/index'>;
}
declare module 'mastarm/__tests__/test-utils/util.js' {
  declare module.exports: $Exports<'mastarm/__tests__/test-utils/util'>;
}
declare module 'mastarm/lib/babel-config.js' {
  declare module.exports: $Exports<'mastarm/lib/babel-config'>;
}
declare module 'mastarm/lib/browserify.js' {
  declare module.exports: $Exports<'mastarm/lib/browserify'>;
}
declare module 'mastarm/lib/budo.js' {
  declare module.exports: $Exports<'mastarm/lib/budo'>;
}
declare module 'mastarm/lib/build.js' {
  declare module.exports: $Exports<'mastarm/lib/build'>;
}
declare module 'mastarm/lib/css-transform.js' {
  declare module.exports: $Exports<'mastarm/lib/css-transform'>;
}
declare module 'mastarm/lib/flyle.js' {
  declare module.exports: $Exports<'mastarm/lib/flyle'>;
}
declare module 'mastarm/lib/fs-promise.js' {
  declare module.exports: $Exports<'mastarm/lib/fs-promise'>;
}
declare module 'mastarm/lib/jest-preprocessor.js' {
  declare module.exports: $Exports<'mastarm/lib/jest-preprocessor'>;
}
declare module 'mastarm/lib/jest.js' {
  declare module.exports: $Exports<'mastarm/lib/jest'>;
}
declare module 'mastarm/lib/js-build.js' {
  declare module.exports: $Exports<'mastarm/lib/js-build'>;
}
declare module 'mastarm/lib/js-transform.js' {
  declare module.exports: $Exports<'mastarm/lib/js-transform'>;
}
declare module 'mastarm/lib/lint-messages.js' {
  declare module.exports: $Exports<'mastarm/lib/lint-messages'>;
}
declare module 'mastarm/lib/load-config.js' {
  declare module.exports: $Exports<'mastarm/lib/load-config'>;
}
declare module 'mastarm/lib/logger.js' {
  declare module.exports: $Exports<'mastarm/lib/logger'>;
}
declare module 'mastarm/lib/pkg.js' {
  declare module.exports: $Exports<'mastarm/lib/pkg'>;
}
declare module 'mastarm/lib/prepublish.js' {
  declare module.exports: $Exports<'mastarm/lib/prepublish'>;
}
declare module 'mastarm/lib/push-to-s3.js' {
  declare module.exports: $Exports<'mastarm/lib/push-to-s3'>;
}
declare module 'mastarm/lib/util.js' {
  declare module.exports: $Exports<'mastarm/lib/util'>;
}
