// flow-typed signature: 838ece5e3e2ba7df7725b8a4b8165161
// flow-typed version: <<STUB>>/react-select-geocoder_v^1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select-geocoder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select-geocoder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select-geocoder/build/index' {
  declare module.exports: any;
}

declare module 'react-select-geocoder/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-select-geocoder/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-select-geocoder/example' {
  declare module.exports: any;
}

declare module 'react-select-geocoder/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select-geocoder/build/index.js' {
  declare module.exports: $Exports<'react-select-geocoder/build/index'>;
}
declare module 'react-select-geocoder/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-select-geocoder/coverage/lcov-report/prettify'>;
}
declare module 'react-select-geocoder/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-select-geocoder/coverage/lcov-report/sorter'>;
}
declare module 'react-select-geocoder/example.js' {
  declare module.exports: $Exports<'react-select-geocoder/example'>;
}
declare module 'react-select-geocoder/index' {
  declare module.exports: $Exports<'react-select-geocoder'>;
}
declare module 'react-select-geocoder/index.js' {
  declare module.exports: $Exports<'react-select-geocoder'>;
}
declare module 'react-select-geocoder/index.test.js' {
  declare module.exports: $Exports<'react-select-geocoder/index.test'>;
}
