// flow-typed signature: 6bd2ab0aa8eb4f4cdd1ca374137b0414
// flow-typed version: <<STUB>>/transitive-js_v^0.11.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transitive-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transitive-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transitive-js/__tests__/util/index' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/journey' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/network' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/path' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/pathsegment' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/pattern' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/patterngroup' {
  declare module.exports: any;
}

declare module 'transitive-js/build/core/route' {
  declare module.exports: any;
}

declare module 'transitive-js/build/display/d3.geo.tile' {
  declare module.exports: any;
}

declare module 'transitive-js/build/display/display' {
  declare module.exports: any;
}

declare module 'transitive-js/build/display/draw-grid' {
  declare module.exports: any;
}

declare module 'transitive-js/build/display/legend' {
  declare module.exports: any;
}

declare module 'transitive-js/build/display/tile-layer' {
  declare module.exports: any;
}

declare module 'transitive-js/build/graph/edge' {
  declare module.exports: any;
}

declare module 'transitive-js/build/graph/edgegroup' {
  declare module.exports: any;
}

declare module 'transitive-js/build/graph/graph' {
  declare module.exports: any;
}

declare module 'transitive-js/build/graph/vertex' {
  declare module.exports: any;
}

declare module 'transitive-js/build/labeler/label' {
  declare module.exports: any;
}

declare module 'transitive-js/build/labeler/labeledgegroup' {
  declare module.exports: any;
}

declare module 'transitive-js/build/labeler/labeler' {
  declare module.exports: any;
}

declare module 'transitive-js/build/labeler/pointlabel' {
  declare module.exports: any;
}

declare module 'transitive-js/build/labeler/segmentlabel' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/multipoint' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/place' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/point' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/pointcluster' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/pointclustermap' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/stop' {
  declare module.exports: any;
}

declare module 'transitive-js/build/point/turn' {
  declare module.exports: any;
}

declare module 'transitive-js/build/renderer/default-renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/build/renderer/renderededge' {
  declare module.exports: any;
}

declare module 'transitive-js/build/renderer/renderedsegment' {
  declare module.exports: any;
}

declare module 'transitive-js/build/renderer/renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/build/renderer/wireframe-renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/build/styler/styler' {
  declare module.exports: any;
}

declare module 'transitive-js/build/styler/styles' {
  declare module.exports: any;
}

declare module 'transitive-js/build/transitive' {
  declare module.exports: any;
}

declare module 'transitive-js/build/util/index' {
  declare module.exports: any;
}

declare module 'transitive-js/build/util/interpolate-line' {
  declare module.exports: any;
}

declare module 'transitive-js/build/util/polyline' {
  declare module.exports: any;
}

declare module 'transitive-js/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'transitive-js/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/journey' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/network' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/path' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/pathsegment' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/pattern' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/patterngroup' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/core/route' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/display/d3.geo.tile' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/display/display' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/display/draw-grid' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/display/legend' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/display/tile-layer' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/graph/edge' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/graph/edgegroup' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/graph/graph' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/graph/vertex' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/labeler/label' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/labeler/labeledgegroup' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/labeler/labeler' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/labeler/pointlabel' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/labeler/segmentlabel' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/multipoint' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/place' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/point' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/pointcluster' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/pointclustermap' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/stop' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/point/turn' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/renderer/default-renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/renderer/renderededge' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/renderer/renderedsegment' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/renderer/renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/renderer/wireframe-renderer' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/styler/styler' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/styler/styles' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/transitive' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/util/index' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/util/interpolate-line' {
  declare module.exports: any;
}

declare module 'transitive-js/lib/util/polyline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transitive-js/__tests__/util/index.js' {
  declare module.exports: $Exports<'transitive-js/__tests__/util/index'>;
}
declare module 'transitive-js/build/core/journey.js' {
  declare module.exports: $Exports<'transitive-js/build/core/journey'>;
}
declare module 'transitive-js/build/core/network.js' {
  declare module.exports: $Exports<'transitive-js/build/core/network'>;
}
declare module 'transitive-js/build/core/path.js' {
  declare module.exports: $Exports<'transitive-js/build/core/path'>;
}
declare module 'transitive-js/build/core/pathsegment.js' {
  declare module.exports: $Exports<'transitive-js/build/core/pathsegment'>;
}
declare module 'transitive-js/build/core/pattern.js' {
  declare module.exports: $Exports<'transitive-js/build/core/pattern'>;
}
declare module 'transitive-js/build/core/patterngroup.js' {
  declare module.exports: $Exports<'transitive-js/build/core/patterngroup'>;
}
declare module 'transitive-js/build/core/route.js' {
  declare module.exports: $Exports<'transitive-js/build/core/route'>;
}
declare module 'transitive-js/build/display/d3.geo.tile.js' {
  declare module.exports: $Exports<'transitive-js/build/display/d3.geo.tile'>;
}
declare module 'transitive-js/build/display/display.js' {
  declare module.exports: $Exports<'transitive-js/build/display/display'>;
}
declare module 'transitive-js/build/display/draw-grid.js' {
  declare module.exports: $Exports<'transitive-js/build/display/draw-grid'>;
}
declare module 'transitive-js/build/display/legend.js' {
  declare module.exports: $Exports<'transitive-js/build/display/legend'>;
}
declare module 'transitive-js/build/display/tile-layer.js' {
  declare module.exports: $Exports<'transitive-js/build/display/tile-layer'>;
}
declare module 'transitive-js/build/graph/edge.js' {
  declare module.exports: $Exports<'transitive-js/build/graph/edge'>;
}
declare module 'transitive-js/build/graph/edgegroup.js' {
  declare module.exports: $Exports<'transitive-js/build/graph/edgegroup'>;
}
declare module 'transitive-js/build/graph/graph.js' {
  declare module.exports: $Exports<'transitive-js/build/graph/graph'>;
}
declare module 'transitive-js/build/graph/vertex.js' {
  declare module.exports: $Exports<'transitive-js/build/graph/vertex'>;
}
declare module 'transitive-js/build/labeler/label.js' {
  declare module.exports: $Exports<'transitive-js/build/labeler/label'>;
}
declare module 'transitive-js/build/labeler/labeledgegroup.js' {
  declare module.exports: $Exports<'transitive-js/build/labeler/labeledgegroup'>;
}
declare module 'transitive-js/build/labeler/labeler.js' {
  declare module.exports: $Exports<'transitive-js/build/labeler/labeler'>;
}
declare module 'transitive-js/build/labeler/pointlabel.js' {
  declare module.exports: $Exports<'transitive-js/build/labeler/pointlabel'>;
}
declare module 'transitive-js/build/labeler/segmentlabel.js' {
  declare module.exports: $Exports<'transitive-js/build/labeler/segmentlabel'>;
}
declare module 'transitive-js/build/point/multipoint.js' {
  declare module.exports: $Exports<'transitive-js/build/point/multipoint'>;
}
declare module 'transitive-js/build/point/place.js' {
  declare module.exports: $Exports<'transitive-js/build/point/place'>;
}
declare module 'transitive-js/build/point/point.js' {
  declare module.exports: $Exports<'transitive-js/build/point/point'>;
}
declare module 'transitive-js/build/point/pointcluster.js' {
  declare module.exports: $Exports<'transitive-js/build/point/pointcluster'>;
}
declare module 'transitive-js/build/point/pointclustermap.js' {
  declare module.exports: $Exports<'transitive-js/build/point/pointclustermap'>;
}
declare module 'transitive-js/build/point/stop.js' {
  declare module.exports: $Exports<'transitive-js/build/point/stop'>;
}
declare module 'transitive-js/build/point/turn.js' {
  declare module.exports: $Exports<'transitive-js/build/point/turn'>;
}
declare module 'transitive-js/build/renderer/default-renderer.js' {
  declare module.exports: $Exports<'transitive-js/build/renderer/default-renderer'>;
}
declare module 'transitive-js/build/renderer/renderededge.js' {
  declare module.exports: $Exports<'transitive-js/build/renderer/renderededge'>;
}
declare module 'transitive-js/build/renderer/renderedsegment.js' {
  declare module.exports: $Exports<'transitive-js/build/renderer/renderedsegment'>;
}
declare module 'transitive-js/build/renderer/renderer.js' {
  declare module.exports: $Exports<'transitive-js/build/renderer/renderer'>;
}
declare module 'transitive-js/build/renderer/wireframe-renderer.js' {
  declare module.exports: $Exports<'transitive-js/build/renderer/wireframe-renderer'>;
}
declare module 'transitive-js/build/styler/styler.js' {
  declare module.exports: $Exports<'transitive-js/build/styler/styler'>;
}
declare module 'transitive-js/build/styler/styles.js' {
  declare module.exports: $Exports<'transitive-js/build/styler/styles'>;
}
declare module 'transitive-js/build/transitive.js' {
  declare module.exports: $Exports<'transitive-js/build/transitive'>;
}
declare module 'transitive-js/build/util/index.js' {
  declare module.exports: $Exports<'transitive-js/build/util/index'>;
}
declare module 'transitive-js/build/util/interpolate-line.js' {
  declare module.exports: $Exports<'transitive-js/build/util/interpolate-line'>;
}
declare module 'transitive-js/build/util/polyline.js' {
  declare module.exports: $Exports<'transitive-js/build/util/polyline'>;
}
declare module 'transitive-js/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'transitive-js/coverage/lcov-report/prettify'>;
}
declare module 'transitive-js/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'transitive-js/coverage/lcov-report/sorter'>;
}
declare module 'transitive-js/lib/core/journey.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/journey'>;
}
declare module 'transitive-js/lib/core/network.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/network'>;
}
declare module 'transitive-js/lib/core/path.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/path'>;
}
declare module 'transitive-js/lib/core/pathsegment.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/pathsegment'>;
}
declare module 'transitive-js/lib/core/pattern.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/pattern'>;
}
declare module 'transitive-js/lib/core/patterngroup.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/patterngroup'>;
}
declare module 'transitive-js/lib/core/route.js' {
  declare module.exports: $Exports<'transitive-js/lib/core/route'>;
}
declare module 'transitive-js/lib/display/d3.geo.tile.js' {
  declare module.exports: $Exports<'transitive-js/lib/display/d3.geo.tile'>;
}
declare module 'transitive-js/lib/display/display.js' {
  declare module.exports: $Exports<'transitive-js/lib/display/display'>;
}
declare module 'transitive-js/lib/display/draw-grid.js' {
  declare module.exports: $Exports<'transitive-js/lib/display/draw-grid'>;
}
declare module 'transitive-js/lib/display/legend.js' {
  declare module.exports: $Exports<'transitive-js/lib/display/legend'>;
}
declare module 'transitive-js/lib/display/tile-layer.js' {
  declare module.exports: $Exports<'transitive-js/lib/display/tile-layer'>;
}
declare module 'transitive-js/lib/graph/edge.js' {
  declare module.exports: $Exports<'transitive-js/lib/graph/edge'>;
}
declare module 'transitive-js/lib/graph/edgegroup.js' {
  declare module.exports: $Exports<'transitive-js/lib/graph/edgegroup'>;
}
declare module 'transitive-js/lib/graph/graph.js' {
  declare module.exports: $Exports<'transitive-js/lib/graph/graph'>;
}
declare module 'transitive-js/lib/graph/vertex.js' {
  declare module.exports: $Exports<'transitive-js/lib/graph/vertex'>;
}
declare module 'transitive-js/lib/labeler/label.js' {
  declare module.exports: $Exports<'transitive-js/lib/labeler/label'>;
}
declare module 'transitive-js/lib/labeler/labeledgegroup.js' {
  declare module.exports: $Exports<'transitive-js/lib/labeler/labeledgegroup'>;
}
declare module 'transitive-js/lib/labeler/labeler.js' {
  declare module.exports: $Exports<'transitive-js/lib/labeler/labeler'>;
}
declare module 'transitive-js/lib/labeler/pointlabel.js' {
  declare module.exports: $Exports<'transitive-js/lib/labeler/pointlabel'>;
}
declare module 'transitive-js/lib/labeler/segmentlabel.js' {
  declare module.exports: $Exports<'transitive-js/lib/labeler/segmentlabel'>;
}
declare module 'transitive-js/lib/point/multipoint.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/multipoint'>;
}
declare module 'transitive-js/lib/point/place.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/place'>;
}
declare module 'transitive-js/lib/point/point.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/point'>;
}
declare module 'transitive-js/lib/point/pointcluster.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/pointcluster'>;
}
declare module 'transitive-js/lib/point/pointclustermap.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/pointclustermap'>;
}
declare module 'transitive-js/lib/point/stop.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/stop'>;
}
declare module 'transitive-js/lib/point/turn.js' {
  declare module.exports: $Exports<'transitive-js/lib/point/turn'>;
}
declare module 'transitive-js/lib/renderer/default-renderer.js' {
  declare module.exports: $Exports<'transitive-js/lib/renderer/default-renderer'>;
}
declare module 'transitive-js/lib/renderer/renderededge.js' {
  declare module.exports: $Exports<'transitive-js/lib/renderer/renderededge'>;
}
declare module 'transitive-js/lib/renderer/renderedsegment.js' {
  declare module.exports: $Exports<'transitive-js/lib/renderer/renderedsegment'>;
}
declare module 'transitive-js/lib/renderer/renderer.js' {
  declare module.exports: $Exports<'transitive-js/lib/renderer/renderer'>;
}
declare module 'transitive-js/lib/renderer/wireframe-renderer.js' {
  declare module.exports: $Exports<'transitive-js/lib/renderer/wireframe-renderer'>;
}
declare module 'transitive-js/lib/styler/styler.js' {
  declare module.exports: $Exports<'transitive-js/lib/styler/styler'>;
}
declare module 'transitive-js/lib/styler/styles.js' {
  declare module.exports: $Exports<'transitive-js/lib/styler/styles'>;
}
declare module 'transitive-js/lib/transitive.js' {
  declare module.exports: $Exports<'transitive-js/lib/transitive'>;
}
declare module 'transitive-js/lib/util/index.js' {
  declare module.exports: $Exports<'transitive-js/lib/util/index'>;
}
declare module 'transitive-js/lib/util/interpolate-line.js' {
  declare module.exports: $Exports<'transitive-js/lib/util/interpolate-line'>;
}
declare module 'transitive-js/lib/util/polyline.js' {
  declare module.exports: $Exports<'transitive-js/lib/util/polyline'>;
}
