// flow-typed signature: 3e4c6876e1ae4e62af01567ab3263f26
// flow-typed version: <<STUB>>/@conveyal/lonlat_v^1.3.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@conveyal/lonlat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@conveyal/lonlat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@conveyal/lonlat/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@conveyal/lonlat/index' {
  declare module.exports: $Exports<'@conveyal/lonlat'>;
}
declare module '@conveyal/lonlat/index.js' {
  declare module.exports: $Exports<'@conveyal/lonlat'>;
}
declare module '@conveyal/lonlat/index.test.js' {
  declare module.exports: $Exports<'@conveyal/lonlat/index.test'>;
}
