// flow-typed signature: e0a703eb3faee57cff6e77935e87146e
// flow-typed version: <<STUB>>/@conveyal/woonerf_v^3.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@conveyal/woonerf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@conveyal/woonerf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@conveyal/woonerf/__mocks__/auth0-lock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/auth0' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/components/auth0-lock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/components/icon' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/components/pure' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/fetch' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/html' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/message' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/mount' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/reducers/user' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/store/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/store/multi' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/__tests__/src/store/promise' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/actions/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/actions/user' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/auth0' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/components/auth0-lock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/components/icon' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/components/pure' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/fetch' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/html' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/message' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/mount' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/reducers/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/reducers/user' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/actions/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/actions/user' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/auth0' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/components/auth0-lock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/components/icon' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/components/pure' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/fetch' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/html' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/message' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/mount' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/reducers/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/reducers/user' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/multi' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/promise' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/store.development' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/store.mock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/src/store/store.production' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/index' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/multi' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/promise' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/store.development' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/store.mock' {
  declare module.exports: any;
}

declare module '@conveyal/woonerf/store/store.production' {
  declare module.exports: any;
}

// Filename aliases
declare module '@conveyal/woonerf/__mocks__/auth0-lock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__mocks__/auth0-lock'>;
}
declare module '@conveyal/woonerf/__tests__/src/auth0.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/auth0'>;
}
declare module '@conveyal/woonerf/__tests__/src/components/auth0-lock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/components/auth0-lock'>;
}
declare module '@conveyal/woonerf/__tests__/src/components/icon.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/components/icon'>;
}
declare module '@conveyal/woonerf/__tests__/src/components/pure.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/components/pure'>;
}
declare module '@conveyal/woonerf/__tests__/src/fetch.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/fetch'>;
}
declare module '@conveyal/woonerf/__tests__/src/html.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/html'>;
}
declare module '@conveyal/woonerf/__tests__/src/message.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/message'>;
}
declare module '@conveyal/woonerf/__tests__/src/mount.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/mount'>;
}
declare module '@conveyal/woonerf/__tests__/src/reducers/user.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/reducers/user'>;
}
declare module '@conveyal/woonerf/__tests__/src/store/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/store/index'>;
}
declare module '@conveyal/woonerf/__tests__/src/store/multi.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/store/multi'>;
}
declare module '@conveyal/woonerf/__tests__/src/store/promise.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/__tests__/src/store/promise'>;
}
declare module '@conveyal/woonerf/actions/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/actions/index'>;
}
declare module '@conveyal/woonerf/actions/user.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/actions/user'>;
}
declare module '@conveyal/woonerf/auth0.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/auth0'>;
}
declare module '@conveyal/woonerf/components/auth0-lock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/components/auth0-lock'>;
}
declare module '@conveyal/woonerf/components/icon.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/components/icon'>;
}
declare module '@conveyal/woonerf/components/pure.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/components/pure'>;
}
declare module '@conveyal/woonerf/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/coverage/lcov-report/prettify'>;
}
declare module '@conveyal/woonerf/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/coverage/lcov-report/sorter'>;
}
declare module '@conveyal/woonerf/fetch.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/fetch'>;
}
declare module '@conveyal/woonerf/html.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/html'>;
}
declare module '@conveyal/woonerf/index' {
  declare module.exports: $Exports<'@conveyal/woonerf'>;
}
declare module '@conveyal/woonerf/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf'>;
}
declare module '@conveyal/woonerf/message.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/message'>;
}
declare module '@conveyal/woonerf/mount.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/mount'>;
}
declare module '@conveyal/woonerf/reducers/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/reducers/index'>;
}
declare module '@conveyal/woonerf/reducers/user.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/reducers/user'>;
}
declare module '@conveyal/woonerf/src/actions/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/actions/index'>;
}
declare module '@conveyal/woonerf/src/actions/user.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/actions/user'>;
}
declare module '@conveyal/woonerf/src/auth0.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/auth0'>;
}
declare module '@conveyal/woonerf/src/components/auth0-lock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/components/auth0-lock'>;
}
declare module '@conveyal/woonerf/src/components/icon.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/components/icon'>;
}
declare module '@conveyal/woonerf/src/components/pure.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/components/pure'>;
}
declare module '@conveyal/woonerf/src/fetch.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/fetch'>;
}
declare module '@conveyal/woonerf/src/html.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/html'>;
}
declare module '@conveyal/woonerf/src/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/index'>;
}
declare module '@conveyal/woonerf/src/message.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/message'>;
}
declare module '@conveyal/woonerf/src/mount.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/mount'>;
}
declare module '@conveyal/woonerf/src/reducers/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/reducers/index'>;
}
declare module '@conveyal/woonerf/src/reducers/user.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/reducers/user'>;
}
declare module '@conveyal/woonerf/src/store/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/index'>;
}
declare module '@conveyal/woonerf/src/store/multi.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/multi'>;
}
declare module '@conveyal/woonerf/src/store/promise.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/promise'>;
}
declare module '@conveyal/woonerf/src/store/store.development.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/store.development'>;
}
declare module '@conveyal/woonerf/src/store/store.mock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/store.mock'>;
}
declare module '@conveyal/woonerf/src/store/store.production.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/src/store/store.production'>;
}
declare module '@conveyal/woonerf/store/index.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/index'>;
}
declare module '@conveyal/woonerf/store/multi.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/multi'>;
}
declare module '@conveyal/woonerf/store/promise.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/promise'>;
}
declare module '@conveyal/woonerf/store/store.development.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/store.development'>;
}
declare module '@conveyal/woonerf/store/store.mock.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/store.mock'>;
}
declare module '@conveyal/woonerf/store/store.production.js' {
  declare module.exports: $Exports<'@conveyal/woonerf/store/store.production'>;
}
